name: epg python

on:
  push:
    branches:
      - main  # Modifier selon votre branche principale
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une image Ubuntu

    steps:
    - name: Vérifier le code source
      uses: actions/checkout@v5

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Version de Python à utiliser

    - name: Installer les dépendances
      run: |
        pip install requests  # Installer requests
        # Ajouter d'autres dépendances si nécessaire

    - name: Exécuter le script
      run: |
        python b03/script.py

    - uses: stefanzweifel/git-auto-commit-action@v5 # Valide et renvoie automatiquement tous les fichiers créés ou modifiés à votre dépôt.
      with:
       commit_message: 'Actualisation'

 
