# Ce workflow utilise des actions qui ne sont pas certifiées par GitHub.
# Ils sont fournis par un tiers et sont régis par
# Conditions d’utilisation, politique de confidentialité et support distincts
# documentation.

# Ce workflow intègre Pyre avec la
# Fonction de balayage de code.
#
# Pyre est un vérificateur de type performant pour Python compatible avec
# PEP 484. Pyre peut analyser des bases de code avec des millions de lignes
# de code de manière incrémentielle – fournissant un retour d’information instantané
# aux développeurs lorsqu’ils écrivent du code.
#
# Voir https://pyre-check.org

name: Pyre

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
         name: my-artifact
         path: my_file.txt
         retention-days: 5

      - name: Run Pyre
        uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d
        with:
          # To customize these inputs:
          # See https://github.com/facebook/pyre-action#inputs
          repo-directory: './'
          requirements-path: 'requirements.txt'
