name: Fr2 m3u8

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code source
      uses: actions/checkout@v5

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Installer les dépendances
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        pip install requests

    - name: Connexion au VPN
      id: vpn_step # On donne un ID pour pouvoir tester le statut plus tard
      run: |
        # Création des fichiers à partir des secrets GitHub
        echo "${{ secrets.OPENVPN_CONFIG }}" > config.ovpn
        echo "${{ secrets.OPENVPN_CREDENTIALS }}" > pass.txt
        
        # Modification de la config pour l'auth automatique
        sed -i 's/auth-user-pass/auth-user-pass pass.txt/' config.ovpn
        
        # Lancement OpenVPN (sudo est requis pour l'interface réseau)
        sudo openvpn --config config.ovpn --daemon
        
        # Attente de la connexion (VPNBook peut être lent à répondre)
        echo "Initialisation du tunnel (60s)..."
        sleep 69

        # Vérification stricte du pays
        COUNTRY=$(curl -s https://ipapi.co/country_code/)
        if [ "$COUNTRY" != "FR" ]; then
          echo "::error::Échec de la connexion VPN. Vérifiez le mot de passe VPNBook !"
          exit 1
        fi
        
        # Vérification si l'IP est bien française
        #curl -s https://ipapi.co/json/ | grep -E "ip|country_name"

    - name: Exécuter le script Python
      run: |
        python ${GITHUB_WORKSPACE}/a02/script_fr2.py

    - name: Arrêter le VPN
      if: always()
      run: sudo killall openvpn || true

    - name: Commit des changements
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Actualisation automatique via VPN FR'
